apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-app
  namespace: default
spec:
  dnsNames:
    - devops.goutham.wuaze.com
  secretName: nginx-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
