apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo
  region: ap-south-1
  
vpc:
  id: "vpc-0914010ddce7ba7a9"
  cidr: "172.31.0.0/16"
  subnets:
    private:
      ap-south-1a:
          id: "subnet-0a68adc9a928bcd8c"
          cidr: "172.31.0.0/17"
      ap-south-1b:
          id: "subnet-0fd24db3338abe403" 
          cidr: "172.31.128.0/17"

managnodeGroups:
  - name: spot-ng
    labels:
      lifecycle: Ec2Spot
    #taints:
    #  spotInstance: true:PreferNoSchedule
    privateNetworking: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    volumeSize: 5
    minSize: 1
    maxSize: 1
    instanceType: t3.small
    desiredCapacity: 1
  
    iam:
      withAddonPolicies:
        externalDNS: true
        autoScaler: true
        ebs: true
        efs: true
        cloudWatch: true
        albIngress: true